repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: check-merge-conflict
    - id: check-json
    - id: check-yaml
    - id: check-added-large-files
    - id: no-commit-to-branch
      args: [--branch, main]
- repo: https://github.com/hrialan/pre-commit-dataform
  rev: v1.0.0
  hooks:
    - id: dataform_format
    - id: dataform_compile
